[package]
name = "pi"
version = "0.1.0"
authors = ["Radovan Bast <bast@users.noreply.github.com>"]
description = "Hands-on demo of the Rust programming language."
license = "MIT"
edition = "2018"

[lib]
name = "pi"
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
rand = "0.7.2"
